name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: internal-sandbox-446612
      REGION: asia-south1
      REPO: my-docker-repo
      IMAGE: my-docker-app
      CLUSTER_NAME: my-gke-cluster
      CLUSTER_LOCATION: asia-south1-a
      NAMESPACE: default
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Authenticate GitHub Actions using Workload Identity
    - name: Authenticate to Google Cloud (OIDC)
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: projects/196053730058/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-runner-sa-demo@internal-sandbox-446612.iam.gserviceaccount.com
        token_format: 'access_token'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v3

    - name: Docker Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: asia-south1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
      
    - name: Build and Push Docker Image
      run: |
        sudo docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }} .
        sudo docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.CLUSTER_LOCATION }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ env.IMAGE }} \
        ${{ env.IMAGE }}=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}
        kubectl rollout status deployment/${{ env.IMAGE }} --timeout=60s

  health-check:
    runs-on: self-hosted
    needs: build-deploy
    env:
      HEALTHCHECK_URL: http://my-docker-app.default.svc.cluster.local:5000/health
      IMAGE: my-docker-app
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: my-gke-cluster
        location: asia-south1-a

    - name: Health Check
      id: health
      run: |
        echo "Waiting 30s before health check..."
        sleep 30
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.HEALTHCHECK_URL }})
        echo "Health check returned status $STATUS_CODE"
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "Health check failed!"
          exit 1

    - name: Rollback Deployment (if health check failed)
      if: failure()
      run: |
        echo "Rolling back deployment..."
        kubectl rollout undo deployment/${{ env.IMAGE }}
        kubectl rollout status deployment/${{ env.IMAGE }}
